(deftheme JD
  "Created 2018-01-05.")

(custom-theme-set-faces
 'JD
 '(default ((t (:inherit nil :stipple nil :background "#1e1e1e" :foreground "#9CDCFE" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 140 :width normal :foundry "nil" :family "Operator Mono"))))
 '(cursor ((t (:background "#51afef"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#51afef"))))
 '(highlight ((t (:background "gray20"))))
 '(region ((t (:background "gray17"))))
 '(shadow ((t nil)))
 '(secondary-selection ((t (:background "MediumPurple3"))))
 '(trailing-whitespace ((t (:background "#ff6c6b"))))
 '(font-lock-builtin-face ((t (:foreground "#c678dd"))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-comment-face ((t (:slant italic :foreground "#608b4e"))))
 '(font-lock-constant-face ((t (:foreground "#569cd6" :weight bold))))
 '(font-lock-doc-face ((t (:foreground "#608b4e" :inherit (font-lock-comment-face)))))
 '(font-lock-function-name-face ((t (:foreground "#dcdcaa"))))
 '(font-lock-keyword-face ((t (:foreground "#C586C0"))))
 '(font-lock-negation-char-face ((t (:foreground "#51afef" :inherit (bold)))))
 '(font-lock-preprocessor-face ((t (:foreground "#51afef" :inherit (bold)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit bold :foreground "#51afef" :weight bold))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold :foreground "#51afef" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#ce9178"))))
 '(font-lock-type-face ((t (:foreground "#DCDCAA"))))
 '(font-lock-variable-name-face ((t (:foreground "#9CDCFE"))))
 '(font-lock-warning-face ((t (:foreground "#dd0093" :inherit (warning)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#51afef"))))
 '(link-visited ((t (:foreground "violet" :inherit (link)))))
 '(fringe ((t (:foreground "#3f444a" :inherit (default)))))
 '(header-line ((t (:foreground "#cccccc" :inherit (mode-line)))))
 '(tooltip ((t (:foreground "#bbc2cf" :background "#21242b"))))
 '(mode-line ((t (:box nil))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#bbc2cf"))))
 '(mode-line-emphasis ((t (:foreground "#51afef"))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box nil :foreground "#5B6268" :background "#1d2026"))))
 '(isearch ((t (:weight bold :foreground "#1B2229" :background "#51afef"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:weight bold :foreground "#DFDFDF" :background "#2257A0"))))
 '(match ((t (:weight bold :foreground "#98be65" :background "#1B2229"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(js2-function-call ((t (:inherit default :foreground "#dcdcaa"))))
 '(js2-function-param ((t (:foreground "#9CDCFE"))))
 '(js2-instance-member ((t (:foreground "#dcdcaa"))))
 '(js2-object-property-access ((t (:inherit js2-object-property :foreground "#dcdcaa")))))
  '(js2-keyword-names ((t (:foreground "#2257A0"))))
(provide-theme 'JD)
